"""table names changed

Revision ID: 157b4b97806d
Revises: 5df26eeb9066
Create Date: 2021-04-03 22:04:30.250657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '157b4b97806d'
down_revision = '5df26eeb9066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('comment_id', sa.String(length=200), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('likes',
    sa.Column('lik_id', sa.String(length=200), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('lik_id')
    )
    op.create_table('stacks',
    sa.Column('stack_id', sa.String(length=200), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('stack_id')
    )
    op.drop_table('stack')
    op.drop_table('comment')
    op.drop_table('like')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('lik_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('updated_at', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('lik_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('comment',
    sa.Column('comment_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('comment_text', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('updated_at', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('comment_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('stack',
    sa.Column('stack_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('list_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('book_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('updated_at', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('stack_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('stacks')
    op.drop_table('likes')
    op.drop_table('comments')
    # ### end Alembic commands ###
