"""exchange pk changed

Revision ID: 1c2c94f0eb23
Revises: 99e56afe31c9
Create Date: 2021-04-13 23:37:26.229324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c2c94f0eb23'
down_revision = '99e56afe31c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange', sa.Column('exchange_id', sa.String(length=200), nullable=False))
    op.drop_column('exchange', 'notification_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange', sa.Column('notification_id', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('exchange', 'exchange_id')
    # ### end Alembic commands ###
