"""user model changed

Revision ID: 24fe391279e7
Revises: b7327ac0f66e
Create Date: 2021-04-14 00:24:04.514587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24fe391279e7'
down_revision = 'b7327ac0f66e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification_id', sa.String(length=200), nullable=False))
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_column('users', 'notification_id')
    # ### end Alembic commands ###
