"""notification title

Revision ID: 25706443ad3f
Revises: a09acad84770
Create Date: 2021-09-07 10:42:03.610132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25706443ad3f'
down_revision = 'a09acad84770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_notifications', sa.Column('notification_title', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('push_notifications', 'notification_title')
    # ### end Alembic commands ###
