"""migrating custom push notification table

Revision ID: 2ce7a3f5fd94
Revises: f62c5653ebf2
Create Date: 2021-09-01 13:54:28.048783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce7a3f5fd94'
down_revision = 'f62c5653ebf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_notifications',
    sa.Column('notification_id', sa.String(length=200), nullable=False),
    sa.Column('notification_message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('notification_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('push_notifications')
    # ### end Alembic commands ###
