"""notification model changed

Revision ID: 304b783476f3
Revises: 4fdef8f8d412
Create Date: 2021-05-05 00:39:42.541759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304b783476f3'
down_revision = '4fdef8f8d412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('is_exchange_notification', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'is_exchange_notification')
    # ### end Alembic commands ###
