"""welcome message added to users model

Revision ID: 33ac6935c156
Revises: daba7fe281b6
Create Date: 2021-08-26 11:17:12.191356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33ac6935c156'
down_revision = 'daba7fe281b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('welcome_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'welcome_message')
    # ### end Alembic commands ###
