"""chat model changed

Revision ID: 5582e80da634
Revises: 9b6943ec8deb
Create Date: 2021-08-04 21:41:17.747931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5582e80da634'
down_revision = '9b6943ec8deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('is_for_sale', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'is_for_sale')
    # ### end Alembic commands ###
