"""user model changed

Revision ID: 56dd641d62b0
Revises: 8aed8c6e85ca
Create Date: 2021-04-05 11:48:57.232696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56dd641d62b0'
down_revision = '8aed8c6e85ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location_longitude', sa.String(length=50), nullable=True))
    op.drop_column('users', 'location_longitue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location_longitue', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('users', 'location_longitude')
    # ### end Alembic commands ###
