"""exchange model modified

Revision ID: 6cc3989b4ac7
Revises: eb28fc14484d
Create Date: 2021-04-06 19:48:48.093665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc3989b4ac7'
down_revision = 'eb28fc14484d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange', sa.Column('is_exchange_confirmed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange', 'is_exchange_confirmed')
    # ### end Alembic commands ###
