"""user model changed

Revision ID: 7d4269e9f561
Revises: 24fe391279e7
Create Date: 2021-04-14 00:25:55.780036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d4269e9f561'
down_revision = '24fe391279e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.String(length=200), nullable=False))
    op.drop_column('users', 'notification_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification_id', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
