"""chat model changed

Revision ID: 8776af44f610
Revises: 5582e80da634
Create Date: 2021-08-04 21:43:50.007696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8776af44f610'
down_revision = '5582e80da634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('buy_id', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'buy_id')
    # ### end Alembic commands ###
