"""exchange and notification model changed

Revision ID: 99e56afe31c9
Revises: 1819dad72b8e
Create Date: 2021-04-13 23:37:02.714370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99e56afe31c9'
down_revision = '1819dad72b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange', sa.Column('notification_id', sa.String(length=200), nullable=False))
    op.drop_column('exchange', 'exchange_id')
    op.add_column('notifications', sa.Column('exchange_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'exchange_id')
    op.add_column('exchange', sa.Column('exchange_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_column('exchange', 'notification_id')
    # ### end Alembic commands ###
