"""notification model changed

Revision ID: 9e7b38a2cd25
Revises: 8776af44f610
Create Date: 2021-08-04 23:57:01.854036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7b38a2cd25'
down_revision = '8776af44f610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('is_buy_confirmed', sa.Integer(), nullable=False))
    op.add_column('notifications', sa.Column('is_buy_declined', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'is_buy_declined')
    op.drop_column('notifications', 'is_buy_confirmed')
    # ### end Alembic commands ###
