"""read notifications

Revision ID: a09acad84770
Revises: 2ce7a3f5fd94
Create Date: 2021-09-02 13:06:03.160385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a09acad84770'
down_revision = '2ce7a3f5fd94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('read_notifications',
    sa.Column('read_id', sa.String(length=200), nullable=False),
    sa.Column('notification_id', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('read_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('read_notifications')
    # ### end Alembic commands ###
