"""notification model changed

Revision ID: b7327ac0f66e
Revises: 1c2c94f0eb23
Create Date: 2021-04-13 23:58:30.916916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7327ac0f66e'
down_revision = '1c2c94f0eb23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('to_be_notified_user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'to_be_notified_user_id')
    # ### end Alembic commands ###
