"""comment column changed

Revision ID: c49e470dfda4
Revises: 0a6f0fc94d18
Create Date: 2021-04-04 13:22:39.288614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c49e470dfda4'
down_revision = '0a6f0fc94d18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('c_id', sa.Integer(), nullable=False))
    op.drop_column('comments', 'comment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment_id', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('comments', 'c_id')
    # ### end Alembic commands ###
