"""stacks model added

Revision ID: c907e3b8a1a2
Revises: 4ff90b90beeb
Create Date: 2021-04-02 23:17:59.168818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c907e3b8a1a2'
down_revision = '4ff90b90beeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stack',
    sa.Column('stack_id', sa.String(length=200), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('stack_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stack')
    # ### end Alembic commands ###
