"""team column added to users table

Revision ID: daba7fe281b6
Revises: 9e7b38a2cd25
Create Date: 2021-08-25 12:36:49.413502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'daba7fe281b6'
down_revision = '9e7b38a2cd25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'buy_id',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.add_column('users', sa.Column('is_team', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_team')
    op.alter_column('notifications', 'buy_id',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
