"""followers model created

Revision ID: e5fb0c4ceb5b
Revises: 32fb2b9eaa57
Create Date: 2021-04-24 23:40:06.430317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5fb0c4ceb5b'
down_revision = '32fb2b9eaa57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follow_id', sa.String(length=200), nullable=False),
    sa.Column('follower_user_id', sa.String(length=200), nullable=False),
    sa.Column('followed_user_id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('follow_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
