"""exchange model modified

Revision ID: eb28fc14484d
Revises: 56dd641d62b0
Create Date: 2021-04-06 19:36:23.429409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb28fc14484d'
down_revision = '56dd641d62b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_column('exchange', 'exchanger_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange', sa.Column('exchanger_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('exchange', 'user_id')
    # ### end Alembic commands ###
