"""chat_messages model changed

Revision ID: f62c5653ebf2
Revises: 33ac6935c156
Create Date: 2021-08-26 16:13:38.853429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62c5653ebf2'
down_revision = '33ac6935c156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('is_read', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'is_read')
    # ### end Alembic commands ###
