"""like pk changed

Revision ID: 0b1e7817643d
Revises: e36d15798c3c
Create Date: 2021-04-13 23:10:23.699871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b1e7817643d'
down_revision = 'e36d15798c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('notification_id', sa.String(length=200), nullable=False))
    op.drop_column('likes', 'like_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('like_id', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('likes', 'notification_id')
    # ### end Alembic commands ###
