"""create column name corrected

Revision ID: 1d4e0063b040
Revises: 5dea79a632e1
Create Date: 2021-04-02 13:04:23.650278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d4e0063b040'
down_revision = '5dea79a632e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('created_at', sa.String(length=20), nullable=True))
    op.drop_column('book', 'create_at')
    op.add_column('categories', sa.Column('created_at', sa.String(length=20), nullable=True))
    op.drop_column('categories', 'create_at')
    op.add_column('exchange', sa.Column('created_at', sa.String(length=20), nullable=True))
    op.drop_column('exchange', 'create_at')
    op.add_column('list', sa.Column('created_at', sa.String(length=20), nullable=True))
    op.drop_column('list', 'create_at')
    op.add_column('post', sa.Column('created_at', sa.String(length=20), nullable=True))
    op.drop_column('post', 'create_at')
    op.add_column('users', sa.Column('created_at', sa.String(length=20), nullable=True))
    op.drop_column('users', 'create_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_at', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('users', 'created_at')
    op.add_column('post', sa.Column('create_at', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('post', 'created_at')
    op.add_column('list', sa.Column('create_at', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('list', 'created_at')
    op.add_column('exchange', sa.Column('create_at', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('exchange', 'created_at')
    op.add_column('categories', sa.Column('create_at', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('categories', 'created_at')
    op.add_column('book', sa.Column('create_at', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('book', 'created_at')
    # ### end Alembic commands ###
