"""chat participants and message models added

Revision ID: 322582d7de87
Revises: 7d4269e9f561
Create Date: 2021-04-16 00:44:56.786023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322582d7de87'
down_revision = '7d4269e9f561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('message_id', sa.String(length=200), nullable=False),
    sa.Column('sender_id', sa.String(length=200), nullable=False),
    sa.Column('receiver_id', sa.String(length=200), nullable=False),
    sa.Column('is_message', sa.Integer(), nullable=True),
    sa.Column('is_exchange', sa.Integer(), nullable=True),
    sa.Column('exchange_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('chat_participants',
    sa.Column('p_id', sa.String(length=200), nullable=False),
    sa.Column('user_one_id', sa.String(length=200), nullable=False),
    sa.Column('user_two_id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('p_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_participants')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
