"""books model changed

Revision ID: 4ff90b90beeb
Revises: 1d4e0063b040
Create Date: 2021-04-02 13:13:19.016603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff90b90beeb'
down_revision = '1d4e0063b040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('book_isbn', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'book_isbn')
    # ### end Alembic commands ###
