"""books and exchange models added

Revision ID: 5dea79a632e1
Revises: 17e2a2d1d461
Create Date: 2021-04-02 13:03:37.139476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dea79a632e1'
down_revision = '17e2a2d1d461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_title', sa.String(length=200), nullable=False),
    sa.Column('book_description', sa.Text(), nullable=True),
    sa.Column('book_author', sa.Text(), nullable=True),
    sa.Column('book_cover_image', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_added_from', sa.String(length=200), nullable=False),
    sa.Column('is_available_for_exchange', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('exchange',
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('exchanger_user_id', sa.Integer(), nullable=False),
    sa.Column('to_exchange_with_user_id', sa.Integer(), nullable=False),
    sa.Column('book_to_be_sent_id', sa.Integer(), nullable=False),
    sa.Column('book_to_be_received_id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('exchange_id')
    )
    op.add_column('categories', sa.Column('create_at', sa.String(length=20), nullable=True))
    op.add_column('categories', sa.Column('updated_at', sa.String(length=20), nullable=True))
    op.add_column('list', sa.Column('create_at', sa.String(length=20), nullable=True))
    op.add_column('list', sa.Column('updated_at', sa.String(length=20), nullable=True))
    op.add_column('post', sa.Column('create_at', sa.String(length=20), nullable=True))
    op.add_column('post', sa.Column('updated_at', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('create_at', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'create_at')
    op.drop_column('post', 'updated_at')
    op.drop_column('post', 'create_at')
    op.drop_column('list', 'updated_at')
    op.drop_column('list', 'create_at')
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'create_at')
    op.drop_table('exchange')
    op.drop_table('book')
    # ### end Alembic commands ###
