"""chat messages model changed

Revision ID: ca45b58ac443
Revises: 322582d7de87
Create Date: 2021-04-16 23:39:16.000379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca45b58ac443'
down_revision = '322582d7de87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('p_id', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'p_id')
    # ### end Alembic commands ###
