"""liek model pk corrected

Revision ID: d339d6d3416f
Revises: 157b4b97806d
Create Date: 2021-04-03 22:37:59.104685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd339d6d3416f'
down_revision = '157b4b97806d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('like_id', sa.String(length=200), nullable=False))
    op.drop_column('likes', 'lik_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('lik_id', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('likes', 'like_id')
    # ### end Alembic commands ###
