"""exchange model changed

Revision ID: e186720b79b6
Revises: b1cd6abf753e
Create Date: 2021-04-17 01:44:17.383673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e186720b79b6'
down_revision = 'b1cd6abf753e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange', sa.Column('exchange_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange', 'exchange_message')
    # ### end Alembic commands ###
