"""notifications model added

Revision ID: e36d15798c3c
Revises: 6cc3989b4ac7
Create Date: 2021-04-13 22:48:52.873517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e36d15798c3c'
down_revision = '6cc3989b4ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(length=200), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_like', sa.Integer(), nullable=False),
    sa.Column('is_comment', sa.Integer(), nullable=False),
    sa.Column('is_follow', sa.Integer(), nullable=False),
    sa.Column('is_exchange', sa.Integer(), nullable=False),
    sa.Column('book_to_be_provided_id', sa.Integer(), nullable=False),
    sa.Column('book_requested_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('notification_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
